### ISSUE TITLE
Right arrow skips between inserted texts

### ISSUE THREAD

**Issue by AlexArendsen** [AlexArendsen/At.js#1]
Pressing the right arrow key at the beginning of an inserted text makes the cursor jump to the beginning of the next inserted text.

**Comment by mattrw89** [comment]
This seems really weird.

**Comment by AlexArendsen** [comment]
It is weird. Just figured out it doesn't happen all the time either-- sometimes it'll skip and other times it won't. The behavior appears to be deterministic on the html, at least.

**Comment by AlexArendsen** [comment]
Fixed this issue in #5 by changing the arrow keys and backspace to use Facebook-like behavior inside of inserted texts. As long as everything looks good over there, this issue can be closed!
