### ISSUE TITLE
Delete and Ctrl+Delete don't behave properly on inserted texts

### ISSUE THREAD

**Issue by AlexArendsen** [AlexArendsen/At.js#4]
Using <kbd>Delete</kbd> or <kbd>Ctrl</kbd>+<kbd>Delete</kbd> on an inserted text simply removes text from the inserted text without turning it back into normal text. Removing the entire inserted text will be the best option in this case.

**Comment by mattrw89** [comment]
Just as a note -- you'll probably want to prepare 4 different branches for these fixes. Maybe the Delete, Ctrl+Delete ones can be on the same branch... will make it more likely to be accepted upstream.
